config/routes.rb
ActivityHelper::Application.routes.draw do

  
  
  devise_for :users, :controllers=> { :registrations=> "users/registrations" } do 
      get "/users/sign_out" => "devise/sessions#destroy"
  end 
   get "/messages/get_friends"    
  resources :friendships
   match '/messages/conversation', to: 'messages#conversation', via: [:get]
   match '/users/user', to: 'users#user', via: [:get]
   match '/users/indexes', to: 'users#indexes', via: [:get]
  resources :messages
  
  
  resources :inverse_friendships
  resources :users do 
  
  
        resources :activity_pages, only: [:new,:create] do 

          resources :comments, only: [:new, :create, :show]
        end
  end
 
  get "activity_pages/home"

 

  match '/activity_pages/activity', to: 'activity_pages#activity', via: [:get]
  
  root :to => 'activity_pages#home'

  match '/:id' => 'users#show', via:[:get]
  

  

   

end

app/models/message.rb
class Message < ActiveRecord::Base
	attr_accessible :message
	attr_accessible :recipient_id
	attr_accessible :user_id
	attr_accessible :status

	belongs_to :friendship
	validates :message, presence: true, length: {minimum: 2}
	validates :recipient_id, presence: true
	validates :user_id, presence: true
	

	
	default_scope order: 'messages.created_at DESC'
	belongs_to :recipients, class_name: "User"
	belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	respond_to :html, :xml, :json
	def new
		@message=Message.new

	end
	def create
		

		# @friendship= Friendship.find(params[:recipient_id])
		# @message= @friendship.messages.build(params[:message])
		if params[:recipient_id]
				recipient=User.find(params[:recipient_id])
				@message = current_user.messages.build(:message => params[:message][:message], recipient_id: recipient.id) 
	    else
	    	str=params[:message][:message]
	    	msg=str.gsub(str.scan(/@[a-zA-Z]+/).last, " ")
	    	var=str.scan(/@[a-zA-Z]+/).last
	    	p=var.scan(/[a-zA-Z]+/)


	    	# p=str.scan(/[a-zA-Z]+/)
	    	# str=str.gsub(p.first, " ")
	    	recipient=User.find_by_username(p)
	    	if p.first!=current_user.username
	    	  @message=current_user.messages.build(message:msg, recipient_id:recipient.id)
	        end 
	    end   

		if @message.save

			@messages=current_user.messages.where(recipient_id: recipient.id)
			@inverse_messages = current_user.inverse_messages.where(user_id: recipient.id)
			@allmessages = @messages+@inverse_messages
			
			@message.user=current_user
			 respond_with do |format|
			 	format.html do
			 		if request.xhr?
			 			render partial: 'messages/conversation', layout: false, status: :created, locals: {messages: @allmessages, friend_id: recipient.id}
                    else
						flash[:success]="message sent"
						redirect_to current_user
					end
				end
			end
		else
			flash[:error]="message can't sent"
			redirect_to current_user
		end
	end

	def index
        @friend_id=params[:user_id]
        # logger.debug "------------>> TIME"
        # logger.debug Time.zone.at(params[:after].to_i)
        # @messages = current_user.inverse_messages.select(:created_at)
        # logger.debug @messages
        @messages=current_user.inverse_messages.where("user_id = ? AND created_at > ?", params[:user_id], Time.zone.at(params[:after].to_i+1)).last
        #@messages = current_user.inverse_messages.first
  #       logger.debug "------------------->>> MESSAGE STARTS HERE"
  #       logger.debug @messages
		# respond_with do |format|
		# 	format.js
  #           format.html 
  #       end
		# @friends = current_user.friends.all 
		# @inverse_friends = current_user.inverse_friends.all
	end
	def conversation
	    @friend_id=params[:param1]
	     
		@messages = current_user.messages.where(recipient_id: @friend_id)
		
		@inverse_messages = current_user.inverse_messages.where(user_id: @friend_id)
		@allmessages = @messages+@inverse_messages
		@inverse_messages.update_all(status: true)

		respond_with do |format|
			format.js
            format.html 
            #     if request.xhr?format.js
	            
                   
            #         render partial: 'messages/conversation', layout: false, status: :created, locals: {messages: @allmessages}
            #          flash[:success]="yes"
            #     else
            #         flash[:success]="ok"
            #     end
            # end
        end
	end
	def destroy
		@message = Message.find(params[:id])
		@friend_id = params[:friend_id]
		if @message.destroy
			@messages = current_user.messages.where(recipient_id: @friend_id)
			@inverse_messages = current_user.inverse_messages.where(user_id: @friend_id)
			@allmessages = @messages+@inverse_messages
			respond_with do |format|
				format.js
	            format.html 
	        end
	    end
	end
	def get_friends
		friends=[]
		var="#{params[:q]}"
	
		var1=var.scan(/\w+/).last
		
		all=User.where("username LIKE ?","#{var1}%")
		all.each  do |friend|
		         #if (current_user.friendships.find_by_friend_id(friend.id) || current_user.inverse_friendships.find_by_user_id(friend.id))
				    name= friend.username
				    a=var
				    b=a.gsub(a.scan(/@[a-z]+/).last, "@")+name

					image="http://www.gravatar.com/avatar/" + friend.email
					friends << {value:b, text:name, image:image}
				 #end

        end

		

		render json: friends
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversation_partial.html.erb
<div class="converge" data-id="<%=friend_id%>">
	<% messages.each do |message|%>
		<%= render partial: "new_message_partial", locals: {message: message, friend_id: friend_id} %>
	<%end%>
	




	<div class="new-message">
		<%=form_for :message, url:messages_path(recipient_id: friend_id), remote: true, html: {id: "create_new_message_form"} do |f| %>
			                
			<%= f.text_field :message, class: "message-form2", placeholder: "send new message..."%>
		    <%=f.submit "Send", class: "btn btn-primary msg-sub"%>
	    <%end%>
	</div>
</div>

app/views/messages/_new_message.html.erb
<%=form_for :message, url:messages_path(user_id: current_user, recipient_id: @user.id) do |f| %>
   <%= render partial:'shared/new_message_error', locals:{ message: message } %>
                  <%= f.text_area :message, class: "message-form", placeholder: "send new message..."%>
                  <%=f.submit "Send", class: "btn btn-primary"%>
<% end %>

app/views/messages/_new_message2.html.erb
<%=form_for :message, url:messages_path(recipient_id: friend_id), remote: true, html: {id: "create_new_message_form"} do |f| %>
			                
			<%= f.text_area :message, class: "message-form2", placeholder: "send new message..."%>
		    <%=f.submit "Send", class: "btn btn-primary btn-large"%>

<%end%>

app/views/messages/_new_message_partial.html.erb
<div class="msg-from" data-time="<%= message.created_at.to_i %>">
		    <%=link_to (gravatar_for User.find(message.user_id)), message.user%>
			<%=message.message%>
			<%=link_to (gravatar_for User.find(message.recipient_id)), User.find(message.recipient_id), class: "my-img" %>
			              
</div>
	Sent <%= time_ago_in_words(message.created_at) %> ago.
	<%=link_to "delete", message_path(message.id, friend_id: friend_id), remote: true, :method => :delete %>

app/views/messages/conversation.html.erb
<div class="container">
		<span class="span8 conversation">
		    <div class="conv">Messages</div><hr>
		    <%@allmessages.each do |message|%>
				<div class="msg-from">
				        <%=link_to (gravatar_for User.find(message.user_id)), message.user%>
		                <%=message.message%>
		                <%=link_to (gravatar_for User.find(message.recipient_id)), User.find(message.recipient_id), class: "my-img" %>
		              
		        </div>
		    <%end%>
		   
		    
		</span>
</div>

app/views/messages/conversation.js.erb
$(".converge").replaceWith("<%= escape_javascript(render partial: "messages/conversation_partial", locals: {messages: @allmessages, friend_id: @friend_id})%>");

app/views/messages/destroy.js.erb
$(".converge").replaceWith("<%= escape_javascript(render partial: "messages/conversation", locals: {messages: @allmessages, friend_id: @friend_id})%>");

app/views/messages/index.html.erb
<% provide(:title, 'messages') %>
<div class="hero-unit what">
<%if signed_in?%>
 <div class="container">
		<span class="span3 list-messager">
		    <div class="list-group">
		       <h3>Friends</h3>

		        <% current_user.friendships.each do |friendship|%>
                    <%if friendship.status==true%>
			            <ol>
						    <div class="replace">   
							    <%= link_to (gravatar_for friendship.friend,size:35), "/messages/conversation?param1=#{friendship.friend.id}", remote: true,  class: "mnp" %>
			                    <%= link_to (friendship.friend.username), "/messages/conversation?param1=#{friendship.friend.id}", remote: true, class: "mnp" %>
	                            
	                             <span class="total">T<%=current_user.inverse_messages.where(user_id: friendship.friend.id).count+current_user.messages.where(recipient_id:friendship.friend.id).count%></span>
	                             <span class="unread">U<%=current_user.inverse_messages.where(user_id: friendship.friend.id, status: false).count%></span>
	                        </div>     
                        
		                    
		                 </ol><hr>
		            <%end%>
				<%end%>
				<%current_user.inverse_friendships.each do |inverse_friendship|%>
				    <%if inverse_friendship.status==true%> 
					    <ol>
					    <div class="replace">
							<%= link_to (gravatar_for inverse_friendship.user), "/messages/conversation?param1=#{inverse_friendship.user.id}", remote: true, class: "mnp"%>

						    <%= link_to (inverse_friendship.user.username),  "/messages/conversation?param1=#{inverse_friendship.user.id}", remote: true, class: "mnp"  %>
						   <!--  <%= inverse_friendship.user.id %> -->
							<span class="total">T<%=current_user.inverse_messages.where(user_id: inverse_friendship.user.id).count+current_user.messages.where(recipient_id: inverse_friendship.user.id).count%></span>
							<span class="unread">U<%= current_user.inverse_messages.where(user_id: inverse_friendship.user.id, status: false).count%></span> 
                        </div>   
						</ol><hr>
					<%end%>
				<%end%>
			</div>
        </span>
		    <span class="span8 conversation">
		        <div class="conv">Messages</div><hr>
                <div class="converge">
                    <%current_user.friendships.each do |friendship|%>
                        <%if friendship.status==true%>
                            <%inverse_message = current_user.inverse_messages.where(user_id:friendship.friend.id, status: false)%>
                            <%if inverse_message.any?%>
                                <div class="user-name">new message from <%= friendship.friend.username%></div>
                                <%inverse_message.each do |message|%>

				                        <div class="remain-message">
				                            <%= gravatar_for friendship.friend%>
				                        	<%= message.message%>
				                        	<div class="time">sent <%= time_ago_in_words(message.created_at) %> ago.</div>
				                        </div>
				                <%end%>
                            <%end%>
                        <%end%>
                            
                    <%end%>   
                    <%current_user.inverse_friendships.each do |inverse_friendship|%>
                        <%if inverse_friendship.status==true%>
                            <%inverse_message = current_user.inverse_messages.where(user_id:inverse_friendship.user.id, status: false)%>
                            <%if inverse_message.any?%>
                                <div class="user-name">new message from <%= inverse_friendship.user.username%></div>
                                <%inverse_message.each do |message|%>

				                        <div class="remain-message">
				                            <%= gravatar_for inverse_friendship.friend%>
				                        	<%= message.message%>
				                        	<div class="time">sent <%= time_ago_in_words(message.created_at) %> ago.</div>
				                        </div>
				                <%end%>
                            <%end%>
                        <%end%>
                            
                    <%end%>   
               
               
				
	                <div class="new-message">
					    <%=form_for :message, remote: true, html: {id: "new-form-msg"} do |f| %>
			                
			                <%= f.text_field :message, class: "message-form3 typeahead", placeholder: "send new message..."%>
			                <%=f.submit "Send", class: "btn btn-primary  message-submit"%>
			            <%end%>
			        </div>
			    </div>
			        
		    </span>
		   
		    
 </div>
<%end%>
</div>

app/views/messages/index.js.erb
alert("comments go here.");
$(".converge").prepend("<%= escape_javascript(render partial: "messages/new_message_partial", locals: {message:  @messages, friend_id: @friend_id })%>");