config/routes.rb
ActivityHelper::Application.routes.draw do

  
  
  devise_for :users, :controllers=> { :registrations=> "users/registrations" } do 
      get "/users/sign_out" => "devise/sessions#destroy"
  end 
   get "/messages/get_friends"    
  resources :friendships
   match '/messages/conversation', to: 'messages#conversation', via: [:get]
   match '/users/user', to: 'users#user', via: [:get]
   match '/users/indexes', to: 'users#indexes', via: [:get]
  resources :messages
  
  
  resources :inverse_friendships
  resources :users do 
  
  
        resources :activity_pages, only: [:new,:create] do 

          resources :comments, only: [:new, :create, :show]
        end
  end
 
  get "activity_pages/home"

 

  match '/activity_pages/activity', to: 'activity_pages#activity', via: [:get]
  
  root :to => 'activity_pages#home'

  match '/:id' => 'users#show', via:[:get]
  

  

   

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  attr_accessible :email, :password, :password_confirmation, :username, :name
  #validates :name, presence: false, length: { maximum: 50 }
  validates :username, presence: true, :uniqueness => true, length: { maximum: 30 }
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :activities, dependent: :destroy
  has_many :comments, through: :activities
  has_many :messages
  has_many :recipients, through: :messages
  has_many :inverse_messages, class_name: "Message", foreign_key: "recipient_id"
  has_many :senders, through: :inverse_messages, :source => :user

  def to_param
    username
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :update_sanitized_params, if: :devise_controller?

	def update_sanitized_params
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :email, :password, :password_confirmation) }

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :destroy]

   

	def show
		if @user = User.find_by_username(params[:id])
		  @activities=@user.activities.paginate(page: params[:page])
      @message=Message.new
      @comment=Comment.new

      
      
      
    else
      flash[:notice] = "Sorry! The page you requestes does not exist"
      redirect_to root_url
    end
	end

  def index
    @user=User.all
      
  end
  def user
  end
  def indexes
     @user=User.all
     #raise @user.to_yaml
  end
  
  private
    def signed_in_user
      unless signed_in?
      #store_location
      redirect_to new_user_session_path, notice: "Please sign in." 
    end
  end

  
	
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/index.html.erb
<% provide(:title, '| all-users') %>
 
 
     <div class="list-user">List of All users</div><hr>
    <% @user.each do |user|%>
  <%if user !=current_user%>

    <div class="span12 offset2 ">
        <div class="row">
            <div class="span2">

               <%=link_to (gravatar_for user, size:90), user%><br><br><br>
                <div class="cent"><%=link_to (user.username), user%></div>


            </div>
            <div class="span4">
              
                 <br><br><br><div class="center center-all"><%=user.email%></div>

            </div>
                <br><br><br><div class="center">
                <%if signed_in? %>
                   <span class="ab1">    

			        <%if current_user.friendships.find_by_friend_id(user.id) %>
			            <%if current_user.friendships.find_by_friend_id(user.id).status == FALSE%>
			               <span class="label label-warning">request already sent</span>

			            <%else%>
			               
			               <span class="label label-warning">friends</span>
			               

			            <%end%>      
			        <%elsif current_user.inverse_friendships.find_by_user_id(user.id) %>
			            <%if current_user.inverse_friendships.find_by_user_id(user.id).status == FALSE%>
			               <div class="btn btn-primary"> request already sent</div>
			            <%else%>
			               
			                <span class="label label-warning">friends</span>
			               
			            <%end%>
			      <%else%>
			            <%if user !=current_user%>
			              <span class="label label-warning"><%= link_to "add-as-friend", friendships_path(:friend_id => user.id), :method => :post%></span>
			            <%end%>
			       <%end%>
			</span>
		<%end%>  
           
           	

        </div>
    </div>
  <%end%>  

                </div>
               
        </div>
        
    </div>
                	
   <%end%>

app/views/users/indexes.html.erb
<% provide(:title, '| all-users') %>
 
<div class="hero-unit what">
  
        <div class="row">
    
               
	            
	                <%@user.each do |user|%>
		                <span class="span12 pers-act">
		                   <div class="row">
					            <div class="span2 gravt">

					               <%=link_to (gravatar_for user, size:90), user%><br>
					                <div class="cent"><%=link_to (user.username), user%></div>
					            </div>
					            <div class="span4 gravta">
              
                                  <br><div class="center center-all"><%=user.email%></div>
                                 </div>
                                 
					        </div>

						</span>
				    <%end%>		
						
			    		
		</div>
				
				    
			   
    
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
	<aside class="span3">
		<section>
			<h3>
				<%= gravatar_for @user,size:120 %>
				<%= @user.username %>
       
			</h3>

    <% if signed_in? %>
 

      <%if current_user.friendships.find_by_friend_id(@user.id) %>
            <%if current_user.friendships.find_by_friend_id(@user.id).status == FALSE%>
               <div class="btn"><p> request already sent</p></div> 
            <%else%>
               <div class="btn"><p> friend</p></div>
               
              <div class="msg">
               <%= link_to " send messages", '#', class: "click-link", remote:true%>
              <div class="gsm"> 
                 <%= render partial: 'messages/new_message', locals: { message: @message } %>
              </div>
            </div>
            <%end%>      
      <%elsif current_user.inverse_friendships.find_by_user_id(@user.id) %>
        <%if current_user.inverse_friendships.find_by_user_id(@user.id).status == FALSE%>
            <div class="btn"><p> request already sent</p></div>
        <%else%>
               <div class="btn"><p> friend</p></div>
            <div class="msg">
               <%= link_to " send messages", '#', class: "click-link", remote:true%>
              <div class="gsm"> 
                 <%= render partial: 'messages/new_message', locals: { message: @message } %>
              </div>
            </div>
        <% end %>
      <%else%>
            <%if @user !=current_user%>

               <%=form_for :friendship, url:friendships_path(:friend_id => @user.id), :method => :post do |f| %>
                <%=f.submit "add-as-friend" %>
                <%end%>
                
            <%end%>
       <%end%>
        <%end%>
   
          
    
     

    </section>
   <div class="dfac">
  <%= link_to "see-friends list", '#', class: "click-link", remote:true%>   
    <div class="index">

    <%if @user== current_user%>
           <h3>Friend Requested</h3>
             <ul>
                  <% @user.inverse_friendships.each do |inverse_friendship|%>

                    <% if inverse_friendship.status==false%>
                      <li><%= inverse_friendship.user.username %>
             
                        (<%= link_to "Accept", friendship_path(inverse_friendship), :method => :put%>)
                        (<%= link_to "Decline", inverse_friendship_path(inverse_friendship), :method => :delete  %>)

                      </li>
                    <%end%>
                  <%end%>
              </ul>
    <%end%>
       <h3>Friends</h3>
      <ul>
          <% @user.friendships.each do |friendship| %>
            <%if friendship.status==true%>
               <li>
               <%= link_to (gravatar_for friendship.friend), friendship.friend%>
               <%=link_to (friendship.friend.username), friendship.friend%>
                   <% if @user==current_user %>
                      (<%= link_to "remove", friendship, :method => :delete%>)<hr><hr>
                    <% end %>
              </li>
          <%end%>
          <%end%>
          <% @user.inverse_friendships.each do |inverse_friendship| %>
            <%if inverse_friendship.status==true%>
               <li>
               <%= link_to (gravatar_for inverse_friendship.user), inverse_friendship.user %>
               <%=link_to (inverse_friendship.user.username), inverse_friendship.user%>
                   <% if @user==current_user %>
                   (<%= link_to "remove", inverse_friendship_path(inverse_friendship), :method => :delete%>)<hr>
                      
                    <% end %>
              </li>
          <%end%>
          <%end%>
      </ul>
       
    </div>   
</div>
  <span class="whole">
    
    <%if @user == current_user%>
<div class="abcd">
       <%= link_to "see sent messages", '#', class: "click-link", remote:true%>
       
        <div class="message-list">
            <b>Sent messages</b>
          <% current_user.messages.each do |message|%>
          
           <div class="all-message">
             <%=message.message%><br></br>
             <% user=User.find(message.recipient_id)%>
             <div class="a">sent by you to...<%= user.username %> at <%= time_ago_in_words(message.created_at) %> ago</div>
           </div>
           <%end%>
           
           
        </div>
</div>
<div class="abcd">
          <%= link_to "see recived messages", '#', class: "click-link", remote:true%>
        <div class="message-list">
            <b>recived messages</b>
          <%current_user.inverse_messages.each do |inverse_message|%>
          <%reciver=User.find(inverse_message.user_id)%>
           <div class="all-message">
             <%=inverse_message.message%><br></br>
             <div class="a">sent by...<%= reciver.username %> at <%= time_ago_in_words(inverse_message.created_at) %> ago</div>
           </div>
           <%end%>
           
           
        </div>
</div>
    <%end%>
	</aside>
	</div>
  
     <div class="plural-activity">The user contains <%= pluralize(@user.activities.count, "activity") %>...</div>
      

	<% @activities.each do |activity|%>
      <div class="activity_partial">
        <div class="span12 offset2 ">
                  <div class="row">
                       <div class="span2">
                          <%= link_to (gravatar_for activity.user), activity.user%>

                           <%=link_to activity.user.username, user_path(activity.user) %>
                           
                       </div>

                       <div class="span4">
                          
                             <ol><h4>Category:</h4> <%=activity.category%></ol>

                             <ol><h4>Name:</h4> <%= activity.name%></ol>


                        </div>
                       <ol><h4>Description:</h4> <%=activity.description%></ol>
                  
                  </div>
              <div class="row">
                <div class="comment-class">
                    Posted <%= time_ago_in_words(activity.created_at) %> ago.
                   <%if signed_in?%>
                    <%= link_to "comment", '#', class: "click-link", remote:true%>
                    <% end%>
                 </div>
              </div>
     
            <div class="row">

              <div class="comment-create">

             
                  <% if activity.comments.any? %>
                    <% activity.comments.each do |comment| %> 
                             
                      <%= render partial: 'comments/comment', locals: { comment: comment } %>
                    <%end%>
                  <%end%>
                <% if signed_in? %>
                  <div class="comm-form">
            
                     <%= render partial: 'comments/new_comment', locals: { rahul: activity, comment:@comment} %>
          
                  </div>
                 <%end%> 

                </div>
            </div>
            
        </div> 
      </div> 
        <%= will_paginate @activities %>       
  <%end%>
 
</span>

        
     
	 

 

app/views/users/user.html.erb
<div class="hero-unit what">

  <div class="row">
  	<%=gravatar_for current_user,size:120%>
  	<%=current_user.username%>
  	<%=link_to "Add-as-friends", '#', class: "btn  btn-primary frnd-req"%>
  	<%=link_to "Send-message", '#', class: "btn  btn-primary frnd-req"%>
  	<hr class="hr">
  	    
		<span class=" span2 links">
     <%=link_to "see-send-messages", '#'%>
		  		
		</span>
		<span class="span10 personal-activity">

		  	
          <div class="row">
            <div class="span2">
               <%=gravatar_for current_user, size:100%><br>
               <%=current_user.username%>
            </div>
            <div class="span4">
              <ol><h4>Category:</h4>iiuououou90u90</ol> 
              <ol><h4>Name:</h4> </ol>
            </div>

               <ol><h4>Description:</h4> </ol>
          </div>
          <div class="row">
            <div class="comment-class">
              Posted  ago.

              <%= link_to "comment", '#', class: "click-link", remote:true%>
            </div>
          </div>
        </span>

	</div>
</div>