config/routes.rb
ActivityHelper::Application.routes.draw do

  
  
  devise_for :users, :controllers=> { :registrations=> "users/registrations" } do 
      get "/users/sign_out" => "devise/sessions#destroy"
  end 
   get "/messages/get_friends"    
  resources :friendships
   match '/messages/conversation', to: 'messages#conversation', via: [:get]
   match '/users/user', to: 'users#user', via: [:get]
   match '/users/indexes', to: 'users#indexes', via: [:get]
  resources :messages
  
  
  resources :inverse_friendships
  resources :users do 
  
  
        resources :activity_pages, only: [:new,:create] do 

          resources :comments, only: [:new, :create, :show]
        end
  end
 
  get "activity_pages/home"

 

  match '/activity_pages/activity', to: 'activity_pages#activity', via: [:get]
  
  root :to => 'activity_pages#home'

  match '/:id' => 'users#show', via:[:get]
  

  

   

end

app/controllers/activity_pages_controller.rb
class ActivityPagesController < ApplicationController
  respond_to :html, :xml, :json
	#before_filter :signed_in_user?, only: [:create]
  #  def signed_in_user
  #     unless signed_in?
  # #     #store_location
  #     redirect_to signin_url, notice: "Please sign in." 
  #  end

	def home
		 
		 @activity = current_user.activities.build if signed_in?
     @activities = Activity.paginate(page: params[:page])
     @comment=Comment.new
     @comments=Comment.all

     
	end
	#before_filter :signed_in_user

  def create
    @activity = current_user.activities.build(params[:activity])
    if @activity.save
       @comment=@activity.comments.new
        @comment.user=current_user
      @activities=Activity.paginate(page: params[:page])
      respond_with do |format|
        format.html do 
          if request.xhr?

            render partial: 'activity', layout: false, status: :created, locals: {nures: @activities.first, comment:@comment}
          else
            flash[:success]="activity created"
            redirect_to root_path
          
          end
        end
      end
       
     else
        respond_with do |format|
          format.html do 
          if request.xhr?
            render partial: 'new_post_form', layout: false, status: :error, locals: {activity: @activity, comment:@comment }
          else
            flash[:erro]="can't create activity"
            redirect_to root_path
          
          end

        end
      end
      
    end
  end

  def destroy
  end
  def activity
  end
  

end

app/helpers/activity_pages_helper.rb
module ActivityPagesHelper
end

app/views/activity_pages/_activity.html.erb
  <div class="activity_partial">
      
        <div class="span12 offset2 ">
          <div class="row">
            <div class="span2">
                <%= link_to (gravatar_for nures.user,size:130), nures.user%>

                <%=link_to nures.user.username, nures.user %>
            </div>
            <div class="span4">
              <ol><h4>Category:</h4> <%=nures.category%></ol>
              <ol><h4>Name:</h4> <%= nures.name%></ol>
            </div>

               <ol><h4>Description:</h4> <%=nures.description%></ol>
          </div>
          <div class="row">
            <div class="comment-class">
              Posted <%= time_ago_in_words(nures.created_at) %> ago.

              <%= link_to "comment", '#', class: "click-link", remote:true%>
            </div>
          </div>
          <div class="row">

            <div class="comment-create">

             
                  <% if nures.comments.any? %>
                    <% nures.comments.each do |comment| %>
                                 
                      <%= render partial: 'comments/comment', locals: { comment: comment } %>
                    <%end%>
                  <%end%>
               <div class="comm-form">
            
              <%= render partial: 'comments/new_comment', locals: { rahul: nures, comment:comment} %>
          
             </div>
           
               
            </div>


          </div>
       </div> 
         


</div>

app/views/activity_pages/_new_post_form.html.erb
<div class="hello">
    <%= form_for :activity,url: user_activity_pages_path(current_user), remote: true , html: {id: "create_activity_form"} do |f| %>
           <%= render partial:'shared/error_messages', locals:{ activity: activity } %>
              <div class="custom-select">
                      <%= f.label :category %>   
                     <div class="myselect"> <%= f.select :category,[['select',''],['Sports','sports'],['Food','food'],['Education','Education']]%></div>
              </div>
              <div class="custom-input">
                      <%= f.label :name%>
                      <%= f.text_field :name %>
              </div>
                   <%= f.label :description%>
                   <%= f.text_area :description, class: "descript", placeholder: "Compose new description..." %>
                   <%= f.submit "Post", class: "btn btn-large btn-primary" %>
            
    <% end %>
</div>

app/views/activity_pages/activity.html.erb
<%provide(:title, '| activity page')%>
<h1> activity page</h1>

app/views/activity_pages/home.html.erb
<%provide(:title, ' ') %>


<% if signed_in? %>
<div class="hero-unit">

    <div class="row">
          <div class="profile-pic"><%= gravatar_for current_user,size:150%> </div>
          <div class="image"><%=link_to current_user.username, user_path(current_user) %>
          </div>

      <div class="span6 offset3">

        <div class="new-activity-form">
          <%= render partial: 'activity_pages/new_post_form', locals: { activity: @activity, comment:@comment } %>
        </div>
      </div>
    </div>
</div>

  <div class="activities">
      <%= will_paginate @activities %>
    <% @activities.each do |rahul|%>

       <%= render partial: 'activity_pages/activity', locals: { nures: rahul, comment:@comment} %>
    <% end %>
       
  </div>

  


     

<% else %>
  
<div class="center hero-unit">


  <h1>Welcome to the Activity Helper App</h1>

  <h2>
    This is the home page for the
    <a href= "#">Activity Helper</a>
    
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "rails"), '#' %>
<%end%>