config/routes.rb
ActivityHelper::Application.routes.draw do

  
  
  devise_for :users, :controllers=> { :registrations=> "users/registrations" } do 
      get "/users/sign_out" => "devise/sessions#destroy"
  end 
   get "/messages/get_friends"    
  resources :friendships
   match '/messages/conversation', to: 'messages#conversation', via: [:get]
   match '/users/user', to: 'users#user', via: [:get]
   match '/users/indexes', to: 'users#indexes', via: [:get]
  resources :messages
  
  
  resources :inverse_friendships
  resources :users do 
  
  
        resources :activity_pages, only: [:new,:create] do 

          resources :comments, only: [:new, :create, :show]
        end
  end
 
  get "activity_pages/home"

 

  match '/activity_pages/activity', to: 'activity_pages#activity', via: [:get]
  
  root :to => 'activity_pages#home'

  match '/:id' => 'users#show', via:[:get]
  

  

   

end

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
           <%= link_to image_tag('app.png', height: 235, width: 235, class: "photo"), root_path, class: "mylogo", id: "logo" %>
          
            
        <ul class="nav pull-right">
               <li><%link_to '<i class="icon-user icon-white"></i> jh'.html_safe, '#' %></li>
               <li> 
                  <%= form_tag "#", :class=>"form-search" do %>
                  <%= text_field_tag 'search-box', nil, :class=>"input-medium search-query", placeholder: 'search here' %>
                  <%= submit_tag  'search', :id=>"submit" %>
                  <%end%></li>
                
                <li><%= link_to "Register/Sign-up", new_user_registration_path %></li>
                <li><%= link_to "Activity", activity_pages_activity_path %></li>

               
                
                
                  

              <% if !current_user %>
                <li><%= link_to "Login", new_user_session_path %></li>
                
                     
            <% else %>
             <li><%=link_to '<i class="icon-user icon-white"></i> '.html_safe, '#' %></li>
                <li><%=link_to '<i class="icon-envelope icon-white"></i> '.html_safe, '#' %>
                <!-- <span class="instant-message"><%=current_user.inverse_messages.where(status: false).count%></span> -->
                </li>

               
                
                <li><%=link_to '<i class="icon-globe icon-white"></i> '.html_safe, '#' %></li>
           
              
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                  User <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><%= link_to '<i class="icon-user  "></i>   profile'.html_safe, user_path(current_user)%></li>
                    <li class="divider"></li>
                    <li><%= link_to '<i class="icon-envelope "></i>   Messages'.html_safe, messages_path %></li>
                    <li class="divider"></li>
                    <li><%=link_to '<i class="icon-user"></i>Find friends'.html_safe, users_path %></li>
                     <li class="divider"></li>
                    <li><%=link_to '<i class="icon-wrench"></i>   Setting'.html_safe, '#'%></li>
                    

                 
                    <li class="divider"></li>
                  
                    <li> <%= link_to '<i class="icon-off"></i>   Sign out'.html_safe, destroy_user_session_path, method: "delete" %><li>
                </ul>
              </div>
                 
                  
              
            </li>
            

                   
                   
              <% end %>
          
          
        </ul>
          
        </div>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActivityHelper <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
      <div id="user_nav">
       
      </div>
    </div>

	
	
 <%= render 'layouts/header' %>

     <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
 
 
 <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>-->

    <%= yield %>


</body>
</html>